//generate this using readFile.js
export const arrProjects = [
  {
    name: "Calculator",
    github: "https://github.com/yalcinaksakal/calculator",
    app: "https://yalcinaksakal.github.io/calculator/",
    img: "1calculator.png",
  },
  {
    name: "Drag and drop",
    github: "https://github.com/yalcinaksakal/drag-n-drop",
    app: "https://kanban-board100.netlify.app/",
    img: "2dragAndDrop.png",
  },
  {
    name: "Dice game",
    github: "https://github.com/yalcinaksakal/dicer",
    app: "https://dicer100.netlify.app/",
    img: "3dicer.png",
  },
  {
    name: "Recipe App (MCV, pubSubs)",
    github: "https://github.com/yalcinaksakal/Jason-s-forkify-app",
    app: "https://jasonsforkify.netlify.app/",
    img: "4recipeApp.png",
  },
  {
    name: "Music player web app",
    github: "https://github.com/yalcinaksakal/music-player",
    app: "https://yalcinaksakal.github.io/music-player/",
    img: "5musicPlayer.png",
  },
  {
    name: "Countdown to a specific date",
    github: "https://github.com/yalcinaksakal/countdown",
    app: "https://yalcinaksakal.github.io/countdown/",
    img: "6countDown.png",
  },
  {
    name: "Bookmarks web app",
    github: "https://github.com/yalcinaksakal/bookmarks",
    app: "https://bookmarks100.netlify.app/",
    img: "7bookmarks.png",
  },
  {
    name: "Video player web app",
    github: "https://github.com/yalcinaksakal/video-player",
    app: "https://yalcinaksakal.github.io/video-player/",
    img: "8videoPlayer.png",
  },
  {
    name: "A basic signup page",
    github: "https://github.com/yalcinaksakal/signUp",
    app: "https://yalcinaksakal.github.io/signUp/",
    img: "9signUp.png",
  },
  {
    name: "Spock rock game",
    github: "https://github.com/yalcinaksakal/spock-rock-game",
    app: "https://yalcinaksakal.github.io/spock-rock-game/",
    img: "10spockRockGame.png",
  },
  {
    name: "Dark and light mode",
    github: "https://github.com/yalcinaksakal/darkLight",
    app: "https://darklight100.netlify.app/",
    img: "11darkLightMode.png",
  },
  {
    name: "Explore NASA images",
    github: "https://github.com/yalcinaksakal/NASA-images-api",
    app: "https://yalcinaksakal.github.io/NASA-images-api/",
    img: "12NASAapi.png",
  },
  {
    name: "Math game",
    github: "https://github.com/yalcinaksakal/Math-game",
    app: "https://yalcinaksakal.github.io/Math-game/",
    img: "13mathGame.png",
  },
  {
    name: "Random quotes",
    github: "https://github.com/yalcinaksakal/quoter",
    app: "https://quoter100.netlify.app/",
    img: "14quoter.png",
  },
  {
    name: "Responsive basic website",
    github: "https://github.com/yalcinaksakal/first-website-design",
    app: "https://justfood.netlify.app/",
    img: "15website.png",
  },
  {
    name: "Infinite scroll of images",
    github: "https://github.com/yalcinaksakal/infinite-images",
    app: "https://infinite-images100.netlify.app/",
    img: "16infiniteImages.png",
  },
  {
    name: "Picture in picture app",
    github: "https://github.com/yalcinaksakal/PiP",
    app: "https://pip100.netlify.app/",
    img: "17PiP.png",
  },
  {
    name: "Joke teller app",
    github: "https://github.com/yalcinaksakal/joke-teller",
    app: "https://joker100.netlify.app/",
    img: "18jokeTeller.png",
  },
  {
    name: "Geolocation and country info",
    github: "https://github.com/yalcinaksakal/whereami",
    app: "https://whereami100.netlify.app/",
    img: "19whereAmI.png",
  },
  {
    name: "Splash page",
    github: "https://github.com/yalcinaksakal/splash-page",
    app: "https://yalcinaksakal.github.io/splash-page/",
    img: "20splashPage.png",
  },
  {
    name: "Flex-box sample",
    github: "https://github.com/yalcinaksakal/flexbox-ex",
    app: "https://flex-box-ex.netlify.app/",
    img: "21flexEg.png",
  },
  {
    name: "Workouts (Openmaps/Leaflet)",
    github: "https://github.com/yalcinaksakal/mapty",
    app: "https://mapty100.netlify.app/",
    img: "22mapty.png",
  },
  {
    name: "Animated navigation bar",
    github: "https://github.com/yalcinaksakal/animated-Nav",
    app: "https://yalcinaksakal.github.io/animated-Nav/",
    img: "23animatedNav.png",
  },
  {
    name: "Adding animations from AOS",
    github: "https://github.com/yalcinaksakal/animated-template",
    app: "https://yalcinaksakal.github.io/animated-template/",
    img: "24animatedWebTemplate.png",
  },
  {
    name: "Rotating logo",
    github: "https://github.com/yalcinaksakal/rotating-logo",
    app: "https://logo100.netlify.app/",
    img: "25rotatingLogo.png",
  },
  {
    name: "Basic blog",
    github: "https://github.com/yalcinaksakal/basic-blog",
    app: "https://yalcinaksakal.github.io/basic-blog/",
    img: "26blog.png",
  },
  {
    name: "Codewars and leetcode",
    github: "https://github.com/yalcinaksakal/codewars",
    app: "https://github.com/yalcinaksakal/codewars",
    img: "27codewars.png",
  },
  {
    name: "Promise combinators basics",
    github: "https://github.com/yalcinaksakal/promise-combinators-basics",
    app: "https://github.com/yalcinaksakal/promise-combinators-basics",
    img: "28promiseCombinators.png",
  },
];
