//generate this using readFile.js
export const arrProjects = [
  {
    type: "three",
    name: "Airplane 3D seat selector",
    github: "https://github.com/yalcinaksakal/airPlaneSeatPicker",
    app: "https://air-plane-seat-picker.vercel.app/",
    img: "airplane.png",
  },
  {
    type: "three",
    name: "Maze",
    github: "https://github.com/yalcinaksakal/maze",
    app: "https://maze-wheat.vercel.app/",
    img: "maze.png",
  },
  {
    type: "three",
    name: "Body parts",
    github: "https://github.com/yalcinaksakal/body2",
    app: "https://body2.vercel.app/",
    img: "body2.png",
    passive: true,
  },
  {
    type: "all",
    name: "My LeetCode",
    github: "https://github.com/yalcinaksakal/myLeetCode",
    app: "https://myleetcode.vercel.app/",
    img: "leetcode.png",
  },
  {
    type: "three",
    name: "Space Game",
    github: "https://github.com/yalcinaksakal/space2",
    app: "https://space2.vercel.app/",
    img: "game.png",
  },
  {
    type: "all",
    name: "Incsub task",
    github: "https://github.com/yalcinaksakal/IncsubTask",
    app: "https://incsub-task.vercel.app/",
    img: "task.png",
  },
  {
    type: "all",
    name: "Toys e-commerce site",
    github: "https://github.com/yalcinaksakal/toys",
    app: "https://toys-sepia.vercel.app/",
    img: "toys.png",
  },
  {
    type: "redux&nextJS",
    name: "Sign in/up/keep logged in",
    github: "https://github.com/yalcinaksakal/Progress",
    app: "https://progress-silk.vercel.app/",
    img: "progress.png",
    passive: true,
  },
  {
    type: "nextJS",
    name: "Quote App",
    github: "https://github.com/yalcinaksakal/quoteNextJS",
    app: "https://quote-next-js.vercel.app/",
    img: "router2.jpg",
  },
  {
    type: "react",
    name: "Burger",
    github: "https://github.com/yalcinaksakal/Burger-react",
    app: "https://burger100.netlify.app/",
    img: "burger.jpg",
  },
  {
    type: "three",
    name: "Terrain",
    github: "https://github.com/yalcinaksakal/terrain",
    app: "https://terrain-h64iac4dr-yalcinaksakal.vercel.app/",
    img: "terrain.png",
  },
  {
    type: "three",
    name: "Space",
    github: "https://github.com/yalcinaksakal/three.js",
    app: "https://three-js-jet.vercel.app/",
    img: "threeJS.png",
  },
  {
    name: "Dijkstra",
    github: "https://github.com/yalcinaksakal/dijkstra",
    app: "https://yalcinaksakal.github.io/dijkstra/",
    img: "dijkstra.png",
  },
  {
    name: "Tree",
    github: "https://github.com/yalcinaksakal/Tree",
    app: "https://yalcinaksakal.github.io/Tree/",
    img: "tree.png",
  },
  {
    type: "react",
    name: "3d Body, react-three-fiber",
    github: "https://github.com/yalcinaksakal/3dbody",
    app: "https://3dbody-1god13aim-yalcinaksakal.vercel.app/",
    img: "body.jpg",
  },

  {
    type: "TS",
    name: "Todo List",
    github: "https://github.com/yalcinaksakal/typeScriptReact",
    app: "https://typescript-react100.netlify.app/",
    img: "todos.jpg",
  },

  {
    type: "redux&nextJS",
    name: "Meetups",
    github: "https://github.com/yalcinaksakal/nextJS-2",
    app: "https://next-js-2-tan.vercel.app/",
    img: "meetups.jpg",
  },
  {
    type: "react-router",
    name: "Quote App",
    github: "https://github.com/yalcinaksakal/react-router-demo",
    app: "https://greatquotes100.netlify.app/",
    img: "router2.jpg",
  },

  {
    type: "redux&nextJS",
    name: "Authentication",
    github: "https://github.com/yalcinaksakal/authNext",
    app: "https://auth-next-rose.vercel.app/",
    img: "auth.jpg",
  },
  {
    type: "react",
    name: "Animations",
    github: "https://github.com/yalcinaksakal/reactAnimations",
    app: "https://animations100.netlify.app/",
    img: "animations.jpg",
  },
  {
    type: "react",
    name: "Custom store(not redux)",
    github:
      "https://github.com/yalcinaksakal/custom-Store-instead-of-Context-API-or-Redux",
    app: "https://custom-store.netlify.app/",
    img: "customStore.jpg",
  },
  {
    type: "react",
    name: "Testing a react app ",
    github: "https://github.com/yalcinaksakal/react-testing",
    app: "https://github.com/yalcinaksakal/react-testing",
    img: "testing.jpg",
  },
  {
    type: "react",
    name: "Hooks exercise",
    github: "https://github.com/yalcinaksakal/hooksExercise",
    app: "https://hooks-execise.netlify.app/",
    img: "hooks.jpg",
  },
  {
    type: "redux",
    name: "Redux Toolkit Ex",
    github: "https://github.com/yalcinaksakal/reduxToolkit",
    app: "https://redux-toolkit-async.netlify.app/",
    img: "toolkit.jpg",
  },
  {
    type: "redux",
    name: "Redux Example",
    github: "https://github.com/yalcinaksakal/redux-demo",
    app: "https://reduxtoolkitexample.netlify.app/",
    img: "redux.jpg",
  },

  {
    type: "react-router",
    name: "React router ex",
    github: "https://github.com/yalcinaksakal/withRouter",
    app: "https://react-router100.netlify.app/",
    img: "reactRouter.jpg",
  },
  {
    type: "react",
    name: "Meal Order",
    github: "https://github.com/yalcinaksakal/MealOrder",
    app: "https://meal-order100.netlify.app/",
    img: "meal.jpg",
  },
  {
    type: "react",
    name: "Movies",
    github: "https://github.com/yalcinaksakal/starwars",
    app: "https://movies100.netlify.app/",
    img: "movies.jpg",
  },
  {
    type: "react",
    name: "Expenses",
    github: "https://github.com/yalcinaksakal/expenses",
    app: "https://expenses100.netlify.app/",
    img: "expenses.jpg",
  },
  {
    type: "react",
    name: "Reducer, context ex.",
    github: "https://github.com/yalcinaksakal/useEffect-Context-Reducers",
    app: "https://reducer-example100.netlify.app/",
    img: "login.jpg",
  },
  {
    type: "react",
    name: "To do list",
    github: "https://github.com/yalcinaksakal/ToDoList",
    app: "https://todolist1000.netlify.app/",
    img: "todolist.jpg",
  },
  {
    type: "react",
    name: "Courses",
    github: "https://github.com/yalcinaksakal/react-router-assignment",
    app: "https://courses100.netlify.app/",
    img: "courses.jpg",
  },
  {
    type: "react",
    name: "Monsters ",
    github: "https://github.com/yalcinaksakal/monsters",
    app: "https://monsters.vercel.app/",
    img: "monsters.png",
  },
  {
    type: "react",
    name: "Users",
    github: "https://github.com/yalcinaksakal/userList",
    app: "https://users100.netlify.app/",
    img: "users.jpg",
  },
  {
    type: "react",
    name: "Blog",
    github: "https://github.com/yalcinaksakal/react-fetch",
    app: "https://blog100.netlify.app/",
    img: "blog.png",
  },

  {
    name: "Egger Game",
    github: "https://github.com/yalcinaksakal/egger",
    app: "https://egger.netlify.app/",
    img: "egger.jpg",
  },
  {
    name: "Pong Game",
    github: "https://github.com/yalcinaksakal/pong-game",
    app: "https://yalcinaksakal.github.io/pong-game/",
    img: "pong.png",
  },
  {
    name: "Venture",
    github: "https://github.com/yalcinaksakal/venture",
    app: "https://venture100.netlify.app/",
    img: "venture.jpg",
  },
  {
    name: "Calculator",
    github: "https://github.com/yalcinaksakal/calculator",
    app: "https://yalcinaksakal.github.io/calculator/",
    img: "1calculator.png",
  },
  {
    name: "Drag and drop",
    github: "https://github.com/yalcinaksakal/drag-n-drop",
    app: "https://kanban-board100.netlify.app/",
    img: "2dragAndDrop.png",
  },
  {
    name: "Dice game",
    github: "https://github.com/yalcinaksakal/dicer",
    app: "https://dicer100.netlify.app/",
    img: "3dicer.png",
  },
  {
    name: "Recipe App (MCV, pubSubs)",
    github: "https://github.com/yalcinaksakal/Jason-s-forkify-app",
    app: "https://jasonsforkify.netlify.app/",
    img: "4recipeApp.png",
  },
  {
    name: "Paint Clone",
    github: "https://github.com/yalcinaksakal/paintClone",
    app: "https://yalcinaksakal.github.io/paintClone/",
    img: "paintClone.png",
  },

  {
    name: "Music player web app",
    github: "https://github.com/yalcinaksakal/music-player",
    app: "https://yalcinaksakal.github.io/music-player/",
    img: "5musicPlayer.png",
  },
  {
    name: "Countdown to a specific date",
    github: "https://github.com/yalcinaksakal/countdown",
    app: "https://yalcinaksakal.github.io/countdown/",
    img: "6countDown.png",
  },
  {
    name: "Bookmarks web app",
    github: "https://github.com/yalcinaksakal/bookmarks",
    app: "https://bookmarks100.netlify.app/",
    img: "7bookmarks.png",
  },
  {
    name: "Video player web app",
    github: "https://github.com/yalcinaksakal/video-player",
    app: "https://yalcinaksakal.github.io/video-player/",
    img: "8videoPlayer.png",
  },
  {
    name: "A basic signup page",
    github: "https://github.com/yalcinaksakal/signUp",
    app: "https://yalcinaksakal.github.io/signUp/",
    img: "9signUp.png",
  },
  {
    name: "Spock rock game",
    github: "https://github.com/yalcinaksakal/spock-rock-game",
    app: "https://yalcinaksakal.github.io/spock-rock-game/",
    img: "10spockRockGame.png",
  },
  {
    name: "Dark and light mode",
    github: "https://github.com/yalcinaksakal/darkLight",
    app: "https://darklight100.netlify.app/",
    img: "11darkLightMode.png",
  },
  {
    name: "Explore NASA images",
    github: "https://github.com/yalcinaksakal/NASA-images-api",
    app: "https://yalcinaksakal.github.io/NASA-images-api/",
    img: "12NASAapi.png",
  },
  {
    name: "Math game",
    github: "https://github.com/yalcinaksakal/Math-game",
    app: "https://yalcinaksakal.github.io/Math-game/",
    img: "13mathGame.png",
  },
  {
    name: "Random quotes",
    github: "https://github.com/yalcinaksakal/quoter",
    app: "https://quoter100.netlify.app/",
    img: "14quoter.png",
  },
  {
    name: "Responsive basic website",
    github: "https://github.com/yalcinaksakal/first-website-design",
    app: "https://justfood.netlify.app/",
    img: "15website.png",
  },
  {
    name: "Infinite scroll of images",
    github: "https://github.com/yalcinaksakal/infinite-images",
    app: "https://infinite-images100.netlify.app/",
    img: "16infiniteImages.png",
  },
  {
    name: "Picture in picture app",
    github: "https://github.com/yalcinaksakal/PiP",
    app: "https://pip100.netlify.app/",
    img: "17PiP.png",
  },
  {
    name: "Joke teller app",
    github: "https://github.com/yalcinaksakal/joke-teller",
    app: "https://joker100.netlify.app/",
    img: "18jokeTeller.png",
  },
  {
    name: "Geolocation and country info",
    github: "https://github.com/yalcinaksakal/whereami",
    app: "https://whereami100.netlify.app/",
    img: "19whereAmI.png",
  },
  {
    name: "Splash page",
    github: "https://github.com/yalcinaksakal/splash-page",
    app: "https://yalcinaksakal.github.io/splash-page/",
    img: "20splashPage.png",
  },
  {
    name: "Flex-box sample",
    github: "https://github.com/yalcinaksakal/flexbox-ex",
    app: "https://flex-box-ex.netlify.app/",
    img: "21flexEg.png",
  },
  {
    name: "Workouts (Openmaps/Leaflet)",
    github: "https://github.com/yalcinaksakal/mapty",
    app: "https://mapty100.netlify.app/",
    img: "22mapty.png",
  },
  {
    name: "Animated navigation bar",
    github: "https://github.com/yalcinaksakal/animated-Nav",
    app: "https://yalcinaksakal.github.io/animated-Nav/",
    img: "23animatedNav.png",
  },
  {
    name: "Adding animations from AOS",
    github: "https://github.com/yalcinaksakal/animated-template",
    app: "https://yalcinaksakal.github.io/animated-template/",
    img: "24animatedWebTemplate.png",
  },
  {
    name: "Rotating logo",
    github: "https://github.com/yalcinaksakal/rotating-logo",
    app: "https://logo100.netlify.app/",
    img: "25rotatingLogo.png",
  },
  {
    name: "Basic blog",
    github: "https://github.com/yalcinaksakal/basic-blog",
    app: "https://yalcinaksakal.github.io/basic-blog/",
    img: "26blog.png",
  },
  {
    name: "Codewars and leetcode",
    github: "https://github.com/yalcinaksakal/codewars",
    app: "https://github.com/yalcinaksakal/codewars",
    img: "27codewars.png",
  },
  {
    name: "Promise combinators basics",
    github: "https://github.com/yalcinaksakal/promise-combinators-basics",
    app: "https://github.com/yalcinaksakal/promise-combinators-basics",
    img: "28promiseCombinators.png",
  },
];
